### ISSUE TITLE
dateFormat not working correctly with `onChange` action

### ISSUE THREAD

**Issue by humanchimp** [shipshapecode/ember-flatpickr#136]
Related to #125

Demo app: https://github.com/lytics/flatpickr-demo-app

I closed that issue because it didn't describe the problem correctly.

## This works

```handlebars
{{ember-flatpickr
  value=dateValue
  onChange=null
  dateFormat="m/d/Y"}}
```

_The date is formatted correctly_

## I expected this to work, but it doesn't

```handlebars
{{ember-flatpickr
  value=(readonly dateValue2)
  onChange=(action (mut dateValue2))
  dateFormat="m/d/Y"}}
```

_The date is unformatted_

I created an app demoing this, [the most salient part of which can be found here](https://github.com/lytics/flatpickr-demo-app/blob/master/app/templates/example.hbs)

**Comment by staskij** [comment]
[Twiddle showing the behaviour](https://ember-twiddle.com/8537d10758304de1be7fe7dfcdacac02?openFiles=templates.application.hbs%2C) (strange dateFormats only to double check we're not using any defaults)

The reason for the unformatted date in the latter example is that `ember-flatpickr` `onChange` simply passes the `flatpickr` onChange arguments to the given action.
`flatpickr` onChange arguments are:
  * an array of JS Date
  * a string formatted accordingly to dateFormat with the latest selected date
  * the flatpickr instance

`(action (mut dateValue2))` thus sets dateValue2 to the first passed argument, which is the array of JS Date, so `dateValue2` becomes an array of JS Date and `{{dateValue2}}` prints the array, without any formatting as JS Date doesn't have any information about the formatting.

By not using readonly+onChange we let `flatpickr` handle the value, which goes against the ddau pattern, so using `readonly` allows to use that pattern.

We could change the order of `ember-flatpickr` onChange arguments, so that instead of `dateObjs, dateStr, instance` we have `dateStr, dateObjs, instance` thus `onChange=(action (mut value))` works as expected, but this means that we have a _slight_ difference from flatpickr API, which may be cause of oversight.

Personally I prefer working with JS Date instead of String containing dates, so what I'm using is a wrapper which ensures I'm using readonly in `value` property and `onChange` returns the first element of  the array so that I can use:
```handlebars
{{ember-flatpickr-wrapper
value=value
onChange=(action (mut value))
altInput=true
altFormat="d/m/Y"}}
```
and value is always a JSDate which I may or may not format.
altInput and altFormat allows flatpickr to display a custom format date, without altering what I expect as value type.

**Comment by rwwagner90** [comment]
Thanks for that clarification @staskij! @humanchimp with this in mind, can we close the issue?

**Comment by humanchimp** [comment]
To me, it seems fairly unergonomic to require a wrapper in order to use the component in the DDAU paradigm, considering that DDAU is considered a best practice.

I think it's better to change the order of the arguments, since if someone is using this addon they shouldn't be using flatpickr directly. The original argument order seems like an implementation-level detail.

That said, it sounds like that would be a breaking API change, and not appropriate for minor release.

If you guys want to make the design decision to leave the original argument order, then I suppose we can close this issue, although it seems like it would be a good idea to make a note about the argument order in the documentation, since when I encountered this it seemed like a bug.

I would like to suggest that we at least consider the impact of changing the argument order.

**Comment by rwwagner90** [comment]
@humanchimp it is documented in the README 

```
Whenever a new date is selected, the action onChange will be fired: if you just want the event to set the array of selected dateObject, you can use (action (mut dateValues)) like the example above. Otherwise you should implement you own onChange action.
```

**Comment by humanchimp** [comment]
OK, sorry I missed that. I'll close this issue now
