### ISSUE TITLE
Is it possible to put static elements inside the ember-flatpickr input?

### ISSUE THREAD

**Issue by tracyalison11** [shipshapecode/ember-flatpickr#443]
The usage documentation states that 

> The wrap option for flatpickr causes flatpickr to search its child elements for elements annotated with certain attributes.

Is it possible to just add something static like a left-aligned clock icon? Thank you!

**Comment by tracyalison11** [comment]
I did find a CSS way to hack it in but am still wondering if this is possible. Thanks!

**Comment by rwwagner90** [comment]
@tracyalison11 `wrap` is not supported, but we do provide a workaround in the docs https://shipshapecode.github.io/ember-flatpickr/docs/usage#ember-flatpickr-and-external-elements

**Comment by rwwagner90** [comment]
Please let me know if that works for you. If not, feel free to reopen this issue!

**Comment by validkeys** [comment]
Just an update, It appears that flatpickr's "on click outside" functionality keeps the above working for me -- clicking an external button does not result in the opening of the calendar. Updated example that works for me:

```javascript
{
  pickr = null

  @action
  onReady(selectedDates, dateStr, pickr) {
    this.set('pickr', pickr)
  }

  @action
  toggleDatePicker(e) {
    e.stopPropagation()
    this.pickr.toggle()
  }
}
```

Am I missing something?

**Comment by rwwagner90** [comment]
@validkeys that is basically the example we have in the docs. What is the question here?

**Comment by validkeys** [comment]
@rwwagner90 sorry -- I think there was a typo in my original message. Was just pointing out that the example as is doesn't cause the date picker to open. The click event's propagation needs to be stopped -- otherwise the flatpickr assumes the button click was outside of the input and therefore calls the flatpickr's close method. 

I've added an example twiddle here for you:

https://ember-twiddle.com/18530bb6e9cc612431eff5342f1c5cc9?openFiles=templates.application%5C.hbs%2C

As you can see there, the "With Propagation" button does not result in the date picker being opened (which is the example in the docs). The "Without Propagation" button results in the date picker being opened.

Let me know if I'm missing something

**Comment by rwwagner90** [comment]
@validkeys ah you are correct! Would you like to open a PR to update the example?

**Comment by validkeys** [comment]
@rwwagner90 yeah will do

**Comment by validkeys** [comment]
@rwwagner90 Ok updated the docs. If I was too verbose, let me know. I'm a talker ;) https://github.com/shipshapecode/ember-flatpickr/pull/602

**Comment by rwwagner90** [comment]
Thanks so much @validkeys!
